app: serverless-plaground
service: serverless-playground

frameworkVersion: '2'

custom:
  ########### Grab stage -- stage, set stage
  myStage: ${opt:stage, self:provider.stage}
  myEnvironment:
    MESSAGE:
      prod: 'This is production environment'
      dev: 'This is development environment'
      test: 'WHAT? How did this get here?'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221,
  environment:
    MESSAGE: ${self:custom.myEnvironment.MESSAGE.${self:custom.myStage}}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: ANY
          cors: true
